Create Table user (
userid INT AUTO_INCREMENT = 1000 PRIMARY KEY ,
firstname VARCHAR(255) NOT NULL,
lastname VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL,
userpassword VARCHAR(255) NOT NULL,
dob DATE NOT NULL,
about TEXT
);